<a href="https://colab.research.google.com/github/ANSHTHAKUR07/Somebasics/blob/main/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#slicing

a = 'ansh'



In [ ]:
a[-1]

'h'

In [ ]:
a[0:2]

'an'

In [ ]:
a[1:]

'nsh'

In [ ]:
a[:]

'ansh'

In [ ]:
a[0]

'a'

In [ ]:
# reverse the string

a[::-1]

'hsna'

In [ ]:
#list
#1. python data typ which consist of multiple elements
#2. these elements can be of different data types
#3. define the list with []
#4. list are mutable

In [ ]:
a =[12,23,57,'sumit',True]

In [ ]:
type(a)

list

In [ ]:
a.append("ansh") # to add

In [ ]:
a

[12, 23, 57, True, 'ansh', 'ansh']

In [ ]:
a.remove('ansh')

In [ ]:
a


[12, 23, 57, True, 'ansh']

In [ ]:
#extracting ansh from given list
a[-1]


'ansh'

In [ ]:
a[::-1]

['ansh', True, 57, 23, 12]

In [ ]:
#Tuples
#python data types which consist of multiple elements
#these elements can be different data types
#define()
#tuples are immutable
#uneditable

In [ ]:
a = (12,23,57,'sumit')

In [ ]:
type(a)

tuple

In [ ]:
a.append('ansh')

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
a.remove('ansh')

AttributeError: 'tuple' object has no attribute 'remove'

In [ ]:
#dictionary
#1. key and values
#2. uses curly bracket

In [ ]:
dict = {'ansh':21, 'ram':20,'raj':22}

In [ ]:
dict = {'ansh':[21,45,23], 'amrit':[20,19,13]}

In [ ]:
dict['ansh'][1]

45

In [ ]:
dict

{'ansh': [21, 45, 23], 'amrit': [20, 19, 13]}

In [ ]:
#sets
a ={1,1,2,3,4,5,3}

In [ ]:
a

{1, 2, 3, 4, 5}

In [ ]:
a =[2,2,1,1,3,8,5]

In [ ]:
a.sort()

In [ ]:
a


[1, 1, 2, 2, 3, 5, 8]

In [ ]:
b= set(a)
b = list(b)
b


[1, 2, 3, 5, 8]

In [ ]:
b[1]

2

In [ ]:
a = [1,2,5,3,8,6] #print the alternate element of list

In [ ]:
print(a[::2])

[1, 5, 8]


In [ ]:
#finding length of the list
len(a)

6

In [ ]:
#to remove the dublicate can use set

In [ ]:
# new day 13june,2024

In [ ]:
#taking input from user

In [ ]:
a =  input()

7


In [ ]:
type (a)

str

In [ ]:
a = int(input())
b = int (input())
a+b

1
2


3

In [ ]:
# take the list as an input from the user sperated by space
# input [2 3 5 7]
# output [2,3,5,7]


In [ ]:
a = input().split(" ")

1 2 3 4 5


In [ ]:
a


['1', '2', '3', '4', '5']

In [ ]:
#for single value use int but for multiple use map command


In [ ]:
# take the list as an input from the user sperated by space
# input 2 3 5 7
# output [2,3,5,7]

In [ ]:
a= list(map(int,input().split(" ")))
print (a)

2 3 4 5 7
[2, 3, 4, 5, 7]


In [ ]:
a

[2, 3, 4, 5, 7]

In [ ]:
#take input from user and store in a list and return reverse of the list

In [ ]:
a = list(map(int, input().split(" ")))
print(a)

1 2 3 4 5
[1, 2, 3, 4, 5]


In [ ]:
a[::-1]

[5, 4, 3, 2, 1]

In [ ]:
#take the input as comma seperated and store it in a list

In [ ]:
a = list(map(int, input().split(",")))
a

2,1,4,5


[2, 1, 4, 5]

In [ ]:
#conditional statement

a = 5
if a > 5:
  print("yo")
else:
    print("na na")

na na


In [ ]:
a = 5

if a > 5:
  print("hi")
elif a == 10:
    print("yo")
else:
    print("na na")

na na


In [ ]:
#write a code to take input from user and return weather the number is even or odd

In [ ]:
a = int(input())
if a % 2 == 0:
    print("even")
else:
    print("odd")

2
even


In [ ]:
# write a code which will check wheather the given string is pallindrome or not
#pallidrome is number wile reverseing string comes same

In [ ]:
a = input()
if a==a[::-1]:
    print("pallindrome")
else:
    print("not pallindrome")

12.21
pallindrome


In [ ]:
#write a code with ypu have to take 3 input variable from user and return the lowest value

In [ ]:
a = input()
b = input()
c = input()
if a<=b and a<=c:
    print(a)
elif b<=a and b<=c:
    print(b)
else:
    print(c)

1
1
2
1


In [ ]:
# write a code to check wheather the given year is leap year or not

In [ ]:
year = int(input())
if (year % 4 == 0) or ( year % 100 == 0) or (year % 400 == 0):
    print("leap year")
else:
    print("not leap year")

2021
not leap year


In [ ]:
#looping

In [ ]:
for i in  range (1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
#print all the even number from 1 to 100

In [ ]:

for i in range (1,101):
    if i%2==0:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [ ]:
#printing it into list
x=[]
for i in range (1,101):
    if i%2==0:
        x.append(i)

In [ ]:
x


[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [ ]:
#take the list as an input and return the sum of all elements of the list

In [ ]:
a = list(map(int, input().split(" ")))
x = 0
for i in a:
    x = x + i
print(x)

1 2 1
4


In [ ]:
#write a code to find the factorial of the given number

In [ ]:
a = int(input())
x = 1
for i in range (1,a+1):
    x = x * i
print(x)

4
24


In [ ]:
a = int(input())

for i in range (1,a+1):
  x = 1
  x = x * i
print(x)

5
5


In [ ]:
# write a code to find the factor of the given number and store it into list


In [ ]:
a = int (input())
x =[]
for i in range (1,a+1):
    if a % i == 0:
        x.append(i)
print(x)

1
[1]


In [ ]:
a = int (input())
x =[]
for i in range (1,a+1):
    if a % i == 0:
        x.append(i)
print(x)

24
[1, 2, 3, 4, 6, 8, 12, 24]


In [ ]:
#write a code to print the HCF of the two given number

In [ ]:
a = int(input())
b = int(input())
for i in range (1,a+1):
    if a % i == 0 and b % i == 0:
        x = i
print(x)

24
54
6


In [ ]:
#by sir

In [ ]:
a = int(input())
b = int(input())
hcf = 1
for i in range(i,a+1):
    if(a % i == 0 and b % i == 0):
        hcf = i
print(hcf)

2
10
1


In [ ]:
#write a code to check the number is prime or not

In [ ]:
a = int(input())
for i in range (2,a):
    if a % i == 0:
        print("not prime")
        break
else:
    print("prime")


4
not prime


In [ ]:
#by sir
a = int(input())
x = []
for i in range (1, a+1):
  if a % i==0 :
    x.append(i)
if len(x) > 2:


In [ ]:
#write a code to print 100 to  in reverse direction

In [ ]:
i = 100
while i >= 0:
    print(i)
    i = i - 1

100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0


In [ ]:
#write the factorial code using the while loop
a = int(input())

fact =1
while a>0:
  fact = fact * a
  a = a - 1
print(fact)

6
720


In [ ]:
#write hcf code using while loop

In [ ]:
a = int(input())
b = int(input())
while a != b:
    if a > b:
        a = a - b
    else:
        b = b - a
print(a)


10
20


ZeroDivisionError: integer division or modulo by zero

In [ ]:
#write a code to print below pattern (always use nested loop)
*
**
***
****
*****

In [ ]:
for i in range (1,6):
    for j in range (1,i+1):
        print("*",end="")
    print()

*
**
***
****
*****


In [ ]:
#by sir

for i in range (1,6):
    for j in range (1,i+1):
        print("*",end="")
    print("/r")

*/r
**/r
***/r
****/r
*****/r


In [ ]:
for i in range (1,6):
    for j in range (1,i+1):
      print(i,j)

1 1
2 1
2 2
3 1
3 2
3 3
4 1
4 2
4 3
4 4
5 1
5 2
5 3
5 4
5 5


In [ ]:
# creating function

#def sum (x, y):
#    print(x+y)

In [ ]:
#sum(2,3)

In [ ]:
#write a function to print LCM of two given number
def lcm (x,y):
  hcf = 1
  for i in range (1,x+1):
    if x % i == 0 and y % i == 0:
      hcf = i
  lcm = (x * y) / hcf
  print(lcm)


In [ ]:
lcm(10,20)

20.0


In [ ]:
# 17 june 2024 eveneing class numpy and pandas

In [ ]:
import numpy as np # used to solve the mathematical problems

In [ ]:
lst1 =(2,3,4,6)
lst2 =(1,3,6,2)

In [ ]:
lst1 + lst2

(2, 3, 4, 6, 1, 3, 6, 2)

In [ ]:
arr1 = np.array(lst1)
arr2 =np.array(lst2)


In [ ]:
arr1 + arr2 # simple addition is only happening in between two

array([ 3,  6, 10,  8])

In [ ]:
arr1

array([2, 3, 4, 6])

In [ ]:
arr2

array([1, 3, 6, 2])

In [ ]:
arr1 * 3 # each element is getting multiplied by 3

array([ 6,  9, 12, 18])

In [ ]:
lst1 *3

(2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6)

In [ ]:
#write a code to add 10 to each element of the list without using numpy

In [ ]:
a = [2,3,4,6]
b = []
for num in a:
    b.append(num + 10)

print(b)



[12, 13, 14, 16]


In [ ]:
#by sir
lst1 = [ 2,3,4,6]
lst2 =[ i+10 for i in lst1]
lst2

[12, 13, 14, 16]

In [ ]:
lst1 =np.array[lst1]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
# iloc is index based where as lock is column based

In [ ]:
# add a new col which would check wheather the name starts with vowel or not

In [ ]:
x =[]
a = ['a','e','i','o','u',]

for i in data.name:
  if i[0] in a:
    x.append(True)
  else:
    x.append(False)

NameError: name 'data' is not defined

In [ ]:
data['new_col3'] = x
data

In [ ]:
#add a new column which will have length of the name

In [ ]:
def length(x):
  return (len(x)):

SyntaxError: invalid syntax (<ipython-input-2-d634a0e78a0d>, line 2)

In [ ]:
length("sumit")

NameError: name 'length' is not defined

In [ ]:
data['new_col4'] = data.name.apply(length)

In [ ]:
data

In [ ]:
#add a new col which would have factorial of e_id

In [ ]:
def factorial(x):
  fact =1
  for i in range (1,x+1):
    fact = fact * i
  return (fact)

In [ ]:
factorial (5)

120

In [ ]:
data['new_col5'] = data.e_id.apply(factorial)

NameError: name 'data' is not defined

In [ ]:
data[data.e_id == 4]

In [ ]:
#write a code to extract the e_id < 4 and new_col ='vowel'
data[(data.e_id < 4) & (data.new_col3 == 'Vowels')]

In [ ]:
# join
data = pd.DataFrame({''})
data_2 = pd.DataFrame({''})

In [ ]:
data_3 = pd.merge(data,data_2,left_on = 'e_id', right_on='e_id', how ='inner')

In [ ]:
data_3 = pd.merge(data,data_2,left_on = 'e_id', right_on='e_id', how ='left')